[package]
name = "semver-parser"
version = "0.10.0"
authors = ["Steve Klabnik <steve@steveklabnik.com>"]
edition = "2018"

[dependencies]
pest = "2.1.0"

[dev-dependencies]
pest_generator = "2.1"
proc-macro2 = "1.0"
